### ISSUE TITLE
გამარჯობათ

### ISSUE THREAD

**Issue by vaxoiva** [gamag/ka_GE.spell#1]
ლიბრეში  5.3.0.3 სპელჩეკი არ მუშაობს? ანუ სწორ ვარიანტებს არ მთავაზობს და ვერ დამეხმარებით

**Comment by gamag** [comment]
მართალი ხართ, არ მუშაობდი  - იმედია ეხლა მუშობას. ახალი ვერსიის ინსტალაციის შინ შეიძლება ძველი ვერსია ხელით უნდა წაშალოთ.
